- name: setup-apps-dbs
  hosts: ansible-executor
  tasks:
  - include: roles/db/tasks/postgres_db.yml
    vars:
      db_name: "freshrss"
      db_password: "{{ freshrss_db_password }}"
    tags: 
    - setup-apps
    - setup-apps-dbs
  - include: roles/db/tasks/postgres_db.yml
    vars:
      db_name: "shiori"
      db_password: "{{ shiori_db_password }}"
    tags: 
    - setup-apps
    - setup-apps-dbs
    when: app_shiori_enabled == true
  - include: roles/db/tasks/postgres_db.yml
    vars:
      db_name: "plume"
      db_password: "{{ plume_db_password }}"
    tags: 
    - setup-apps
    - setup-apps-dbs
    when: app_plume_enabled == true


- name: setup-apps
  hosts: master
  roles:
  - role: stream
    tags: 
    - setup-apps
    - stream
  - role: searx
    tags: 
    - setup-apps
    - searx
    when: app_searx_enabled == true
  - role: freshrss
    tags: 
    - setup-apps
    - freshrss
    when: app_freshrss_enabled == true
  - role: droppy
    tags: 
    - setup-apps
    - droppy
    when: app_droppy_enabled == true
  - role: thelounge
    tags: 
    - setup-apps
    - thelounge
    when: app_thelounge_enabled == true
  - role: shiori
    tags: 
    - setup-apps
    - shiori
    when: app_shiori_enabled == true
  - role: plume
    tags: 
    - setup-apps
    - plume
    when: app_plume_enabled == true